name: Build and Push the container

on:
  workflow_dispatch:
  push:
    branches:
    - "master"
    paths-ignore:
    - "**/README.md"
    - "**/*.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set container name
      run: echo "CONTAINER_NAME=workflow-file-tester" >> $GITHUB_ENV
    - name: Set dockerfile location
      run: echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
    - name: Get date and hash
      run: echo "TAG=$(date --iso-8601)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Build container
      run: docker build . --file ${{ env.DOCKERFILE }} --tag ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:${{ env.TAG }}
    - name: Log in to the container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ secrets.PUSH_PACKAGE_USERNAME }}
        password: ${{ secrets.PUSH_PACKAGE_TOKEN }}
    - name: Tag the container as latest
      run: docker tag ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:${{ env.TAG }} ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:latest
    - name: Push the container
      run: docker push ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:${{ env.TAG }} && docker push ghcr.io/hcdp/${{ env.CONTAINER_NAME }}:latest
